language: cpp

matrix:
  include:
    # Ubuntu 14.04 Trusty Tahr
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    # OS X 10.9 Mavericks
    - os: osx
      osx_image: beta-xcode6.2
      compiler: clang
    # OS X 10.11 El Capitan
    - os: osx
      osx_image: xcode7.3
      compiler: clang

# Linux dependencies
# See: https://github.com/gosu/gosu/wiki/Getting-Started-on-Linux
addons:
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-ttf-dev
      - libpango1.0-dev
      - libgl1-mesa-dev
      - libfreeimage-dev
      - libopenal-dev
      - libsndfile1-dev

before_install:
  # Mac dependencies
  # See: https://github.com/gosu/gosu/wiki/Getting-Started-on-OS-X
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update; brew install sdl2; rvm install 2.1; rvm use 2.1; fi
  # Dependencies for 'rake gem' (not for actually using Gosu)
  - gem update --system && gem install rake-compiler

# Minimal git coverage (for now).
branches:
  only:
  - master
git:
  depth: 3

# 'rake gem' relies on this.
env:
  global:
    - GOSU_RELEASE_VERSION=9.9.9

notifications:
  email:
    - info@libgosu.org

install: rake gem && cd "$TRAVIS_BUILD_DIR" && gem install pkg/gosu-9.9.9.gem
script: ruby -rgosu -e 'puts Gosu::VERSION'
