language: cpp

matrix:
  include:
    # Ubuntu 14.04 Trusty Tahr
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    # OS X 10.9 Mavericks
    - os: osx
      osx_image: beta-xcode6.2
      compiler: clang
    # OS X 10.11 El Capitan
    - os: osx
      osx_image: xcode7.3
      compiler: clang

# Linux dependencies
# See: https://github.com/gosu/gosu/wiki/Getting-Started-on-Linux
addons:
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-ttf-dev
      - libpango1.0-dev
      - libgl1-mesa-dev
      - libfreeimage-dev
      - libopenal-dev
      - libsndfile1-dev
      # For Ruby
      - ruby-dev
      # For C++
      - cmake

before_install:
  # Mac dependencies
  # See: https://github.com/gosu/gosu/wiki/Getting-Started-on-OS-X
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update; brew install sdl2; fi
  # To not use RVM - it's been a mess for compiling Gosu on OS X.
  - rvm use system
  # But update the system RubyGems on OS X.
  - if [ $TRAVIS_OS_NAME == osx ]; then sudo gem update --system; fi
  # Dependencies for 'rake gem' (not for actually using Gosu)
  # We have to install binaries into ~ because of Apple's System Integrity Protection.
  - sudo gem install rake rake-compiler --no-ri --no-rdoc -n ~

# Minimal git coverage (for now).
branches:
  only:
  - master
git:
  depth: 3

# 'rake gem' relies on this.
env:
  global:
    - GOSU_RELEASE_VERSION=9.9.9

notifications:
  email:
    - info@libgosu.org

install:
  # Ruby/Gosu
  - ~/rake gem
  - sudo gem install pkg/gosu-9.9.9.gem --no-ri --no-rdoc
  # Gosu for C++ using CMake
  - mkdir -p cmake/build && cd cmake/build && cmake .. && make && sudo make install && cd ../..

script:
  # Ruby/Gosu
  - ruby -rgosu -e 'puts Gosu::VERSION'
  # Compile C++ examples
  - mkdir -p examples/build && cd examples/build && cmake .. && make && cd ../..
